/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/ui/badge/Badge.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardAction: typeof import('./src/components/ui/card/CardAction.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    Carousel: typeof import('./src/components/ui/carousel/Carousel.vue')['default']
    CarouselContent: typeof import('./src/components/ui/carousel/CarouselContent.vue')['default']
    CarouselItem: typeof import('./src/components/ui/carousel/CarouselItem.vue')['default']
    CarouselNext: typeof import('./src/components/ui/carousel/CarouselNext.vue')['default']
    CarouselPrevious: typeof import('./src/components/ui/carousel/CarouselPrevious.vue')['default']
    ContactCard: typeof import('./src/components/ContactCard.vue')['default']
    InfoListItem: typeof import('./src/components/InfoListItem.vue')['default']
    NavigationMenu: typeof import('./src/components/ui/navigation-menu/NavigationMenu.vue')['default']
    NavigationMenuContent: typeof import('./src/components/ui/navigation-menu/NavigationMenuContent.vue')['default']
    NavigationMenuIndicator: typeof import('./src/components/ui/navigation-menu/NavigationMenuIndicator.vue')['default']
    NavigationMenuItem: typeof import('./src/components/ui/navigation-menu/NavigationMenuItem.vue')['default']
    NavigationMenuLink: typeof import('./src/components/ui/navigation-menu/NavigationMenuLink.vue')['default']
    NavigationMenuList: typeof import('./src/components/ui/navigation-menu/NavigationMenuList.vue')['default']
    NavigationMenuTrigger: typeof import('./src/components/ui/navigation-menu/NavigationMenuTrigger.vue')['default']
    NavigationMenuViewport: typeof import('./src/components/ui/navigation-menu/NavigationMenuViewport.vue')['default']
    Progress: typeof import('./src/components/ui/progress/Progress.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./src/components/SectionHeader.vue')['default']
    Separator: typeof import('./src/components/ui/separator/Separator.vue')['default']
    SkillCard: typeof import('./src/components/SkillCard.vue')['default']
    Stepper: typeof import('./src/components/ui/stepper/Stepper.vue')['default']
    StepperDescription: typeof import('./src/components/ui/stepper/StepperDescription.vue')['default']
    StepperIndicator: typeof import('./src/components/ui/stepper/StepperIndicator.vue')['default']
    StepperItem: typeof import('./src/components/ui/stepper/StepperItem.vue')['default']
    StepperSeparator: typeof import('./src/components/ui/stepper/StepperSeparator.vue')['default']
    StepperTitle: typeof import('./src/components/ui/stepper/StepperTitle.vue')['default']
    StepperTrigger: typeof import('./src/components/ui/stepper/StepperTrigger.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}
